# embed_file.cmake
# Usage: cmake -DINPUT=path/to/file -DOUTPUT=path/to/header.h -DVAR_NAME=g_logo_data -P embed_file.cmake
# Reads INPUT as binary, writes a C header with a const unsigned char array + size.

if(NOT EXISTS "${INPUT}")
    message(STATUS "embed_file: ${INPUT} not found, writing empty stub")
    file(WRITE "${OUTPUT}" "// ${VAR_NAME} not available (asset missing)\n"
        "static const unsigned char ${VAR_NAME}[] = {0};\n"
        "static const unsigned int  ${VAR_NAME}_size = 0;\n")
    return()
endif()

file(READ "${INPUT}" raw HEX)

# Convert hex string to comma-separated 0xNN bytes
string(LENGTH "${raw}" hexLen)
set(bytes "")
set(i 0)
while(i LESS hexLen)
    string(SUBSTRING "${raw}" ${i} 2 byte)
    if(bytes STREQUAL "")
        set(bytes "0x${byte}")
    else()
        string(APPEND bytes ", 0x${byte}")
    endif()
    math(EXPR i "${i} + 2")
endwhile()

math(EXPR byteCount "${hexLen} / 2")

file(WRITE "${OUTPUT}"
    "// Auto-generated by cmake/embed_file.cmake — do not edit\n"
    "static const unsigned char ${VAR_NAME}[] = {\n    ${bytes}\n};\n"
    "static const unsigned int  ${VAR_NAME}_size = ${byteCount};\n"
)
message(STATUS "embed_file: embedded ${byteCount} bytes from ${INPUT} -> ${OUTPUT}")
